export enum MoviesTypes {
  LIST_ORIGINALS_MOVIES_REQUEST = '@movies/LIST_ORIGINALS_MOVIES_REQUEST',
  LIST_ORIGINALS_MOVIES_SUCCESS = '@movies/LIST_ORIGINALS_MOVIES_SUCCESS',
  LIST_ORIGINALS_MOVIES_FAILURE = '@movies/LIST_ORIGINALS_MOVIES_FAILURE',

  LIST_TRENDING_MOVIES_REQUEST = '@movies/LIST_TRENDING_MOVIES_REQUEST',
  LIST_TRENDING_MOVIES_SUCCESS = '@movies/LIST_TRENDING_MOVIES_SUCCESS',
  LIST_TRENDING_MOVIES_FAILURE = '@movies/LIST_TRENDING_MOVIES_FAILURE',

  LIST_TOP_RATED_MOVIES_REQUEST = '@movies/LIST_TOP_RATED_MOVIES_REQUEST',
  LIST_TOP_RATED_MOVIES_SUCCESS = '@movies/LIST_TOP_RATED_MOVIES_SUCCESS',
  LIST_TOP_RATED_MOVIES_FAILURE = '@movies/LIST_TOP_RATED_MOVIES_FAILURE',

  LIST_GENRES_MOVIES_REQUEST = '@movies/LIST_GENRES_MOVIES_REQUEST',
  LIST_GENRES_MOVIES_SUCCESS = '@movies/LIST_GENRES_MOVIES_SUCCESS',
  LIST_GENRES_MOVIES_FAILURE = '@movies/LIST_GENRES_MOVIES_FAILURE',

  FIND_MOVIE_INFO_REQUEST = '@movies/FIND_MOVIE_INFO_REQUEST',
  FIND_MOVIE_INFO_SUCCESS = '@movies/FIND_MOVIE_INFO_SUCCESS',
  FIND_MOVIE_INFO_FAILURE = '@movies/FIND_MOVIE_INFO_FAILURE',
}

export enum EMovieKindRequest {
  ACTION = 28,
  COMEDY = 35,
  HORROR = 27,
  ROMANCE = 10749,
  DOCUMENTARY = 99,
}
